/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Teste classUnderTest = new Teste();
        assertTrue(true);
    }
}
