#!/bin/bash
#estSeq01.sh

read -p "Digite o valor do lado: " lado

area = (($lado * $lado));

echo "O resultado da área do quadrado é: ${area} ";


#!/bin/bash
#estSeq2.sh
read -p "Digite o valor do Salário: " salario

reajuste =$(echo "salario + (salario * 0.15)" | bc)

echo "O resultado do Reajuste é: ${reajuste}"


#!/bin/bash
#estSeq3.sh

read -p "Digite o valor da base: " base
read -p "Digite o valor da altura: " altura

area=$(echo "$base * $altura" | bc)

echo "O resultado da area do quadrado é: ${area}"



#!/bin/bash
#estSeq4.sh

read -p "Digite o valor de Graus em Celsius: " celsius

fahrenheit=$(echo "(9 * $celsius + 160) / 5" | bc)

echo "O resultado em Fahrenheit é: ${fahrenheit}"

#!/bin/bash
#estSeq5.sh

read -p "Digite o valor de a: " a
read -p "Digite o valor de b: " b
read -p "Digite o valor de c: " c


delta =$(echo "($b * $b) - (4 * $a * $c)" | bc)
x0 =$(echo "($b + sqrt($delta)) / (2 * $a)" | bc)
x1 =$(echo "($b - sqrt($delta)) / (2 * $a)
" | bc)

echo "O resultado de x0 é ${x0} e de x1 ${x1}"


#!/bin/bash
#estSeq6.sh

read -p "Digite o valor de x: " x
read -p "Digite o valor de y: " y

troca = $a
a = $b
b = $troca

echo "Valor de x agora é ${x} e y ${y}"


#!/bin/bash
#estSeq7.sh

read -p "Digite o Comprimento: " comprimento
read -p "Digite a Largura: " largura
read -p "Digite a Altura: " altura

volume =$(echo "($comprimento * $altura * $largura)" | bc)

echo "O resultado do volume é: ${volume}"


#!/bin/bash
#estSeq8.sh

read -p "Digite o valor do depósito: " deposito
valor=$(echo "$deposito * 0.013" | bc)

echo "O valor é: ${valor}"


#!/bin/bash
#estSeq9.sh

read -p "Digite o valor do primeiro número inteiro: " num1
read -p "Digite o valor do segundo número inteiro: " num2

soma = $(($num1 + $num2))

echo "a soma dos dois é: ${soma}"


#!/bin/bash
#estSeq10.sh

read -p "Digite o valor do primeiro número real: " num1
read -p "Digite o valor do segundo número real: " num2

soma =$(echo "$num1 + $num2" | bc)

echo "a soma dos dois é: ${soma}"




#!/bin/bash
#estSeq11.sh

read -p "Digite o valor do raio: " raio

comprimento=$(echo "(2 * $raio) * 3.14" | bc)

echo "O resultado do comprimento é: ${comprimento}"



#!/bin/bash
#estSeq12.sh

read -p "Digite o ano de nascimento: " anoNasc
read -p "Digite o ano atual: " anoNasc

resltd =$(( ($anoAtual - anoNasc) + 17 ))

echo "Daqui a 17 anos você terá ${resltd}"



#!/bin/bash
#estSeq13.sh

read -p "Digite a quantidade de kilos: " kg

duracaoDias=$(echo "($kg * 1000) / 50" | bc)

echo "O alimento durará ${duracaoDias} dias"


#!/bin/bash
#estSeq14.sh

read -p "Digite o valor do 1° ângulo: " ang1
read -p "Digite o valor do 2° ângulo: " ang2

ang3 = $(( ($ang1 + $ang2) - 180))

echo "O valor do 3° ângulo é ${ang3} graus"



#!/bin/bash
#estSeq15.sh

read -p "Digite o valor do 1° Cateto: " cat1
read -p "Digite o valor do 2° Cateto: " cat2

hip=$(echo "sqrt(cat1 *  cat1) + (cat2 * cat2)" | bc)

echo "O resultado da hipotenusa é ${hip}"


#!/bin/bash
#estSeq16.sh

read -p "Digite a quantidade de horas: " qntH
read -p Digite o valor por hora: " vPHr
read -p "Digite o valor do percentual: " perc             
read -p "Digite a quantidade de dependentes: " dep

saBrut = $((qntH * vPHr))
saLiq =$(echo "($saBrut - ($saBrut * ($perc / 100))) + ($dep * 100) | bc)

echo "O valor do Salário Líquido é de ${saLiq} reais"



#!/bin/bash
#estSeq17.sh

read -p "Digite o tempo de percurso: " tempP
read -p "Digite a velocidade média: " velMed

lGast=$(echo "($tempP * $velMed) / 12" | bc)

echo "A quantidade de litros gastos na viagem foi ${lGast}"

#!/bin/bash
#estSeq18.sh

read -p "Digite o primeiro número: " num1
read -p "Digite o segundo número: " num2

dValor = 0

if [[ "$num1" -gt "$num2" ]]; then
    dValor = $(($num1 - $num2))
else
    dValor = $(($num2 - $num1))
fi

echo "A diferença entre os dois números é de ${dValor}"


#!/bin/bash
#estSeq19.sh

read -p "Digite o primeiro número: " num1
read -p "Digite o segundo número: " num2


if [[ "$num1" -gt "$num2" ]]; then
    echo "o maior número é o primeiro com ${num1}"
else
    echo "o maior número é o segunfo com ${num2}"
fi


#!/bin/bash
#estSeq20.sh

read -p "Digite o valor de a: " a
read -p "Digite o valor de b: " b
read -p "Digite o valor de c: " c


delta =$(echo "($b * $b) - (4 * $a * $c)" | bc)
x0 =$(echo "($b + sqrt($delta)) / (2 * $a)" | bc)
x1 =$(echo "($b - sqrt($delta)) / (2 * $a)
" | bc)

if[[ "$delta" > 0 ]] then
   echo "O resultado de x0 é ${x0} e de x1 ${x1}"
else
   echo "Raiz inexistente e negativa"
fi




#!/bin/bash
#estSeq21.sh

read -p "Digite o valor da primeira nota: "  nota1
read -p "Digite o valor da segunda nota: "  nota2
read -p "Digite o valor da terceira nota: "  nota3
read -p "Digite o valor da quarta nota: "  nota4

media=$(echo "($nota1 + $nota2 + $nota3 + $nota4) / 4" | bc)

if [[ "$media" -gte 6.0 ]] then
   echo "APROVADO"
elif [[ "$media" -lt 3 ]] then
   echo "REPROVADO"
else
   echo "EXAME"


#!/bin/bash
#estSeq22.sh

read -p "Digite o primeiro número: " num1
read -p "Digite o segundo número: " num2


if [[ "$num1" -gt "$num2" ]]; then
    echo "${num1} e ${num2}"
else
    echo "${num2} e ${num1}"
fi


#!/bin/bash
#estSeq23.sh

read -p "Digite o primeiro número: " num1
read -p "Digite o segundo número: " num2
read -p "Digite o terceiro número: " num3
read -p "Digite o quarto número: " num4


if [ "$num4" -gt "$num3" ] then
  echo "A sequência dos números é na seguinte forma: ${num1} ${num2} ${num3} ${num4} "
elif [ "$num4" -gt "$num2" && "$num4" -lt "$num3" ] then
   echo "A sequência dos números é na seguinte forma: ${num1} ${num2} ${num4} ${num3} "
elif [ "$num4" -gt "$num1" && "$num4" -lt "$num2" ] then
    echo "A sequência dos números é na seguinte forma: ${num1} ${num4} ${num2} ${num3}"
else 
    echo "A sequência dos números é na seguinte forma: ${num4} ${num1} ${num2} ${num3}"
fi

#!/bin/bash
#estSeq24.sh

read -p "Digite o número: " num

if [ "$num" % 2 -eq 0 && "$num" % 3 -eq 0] ; then
 echo "O valor é divisível por 2 e 3"
else
 echo "O valor não é divisível por 2 e 3"
fi

#!/bin/bash
#estSeq25.sh

read -p "Digite a hora de início do jogo: " horaInicio
read -p "Digite os minutos de início do jogo: "  minInicio
read -p "Digite a hora de fim do jogo: " horaFim
read -p "Digite os minutos de fim do jogo: " minFim
		
if [ "$horaFim" - "$horaInicio" -lt 0 ] ; then
 duracaoHor=$(( ($horaFim - $horaInicio) + 24 ))
else
 duracaoHor=$(( $horaFim - $horaInicio ))
fi

if [ "$minFim" - "$minInicio" -lt 0 ] ; then
 duracaoMin=$(( ($minFim - $minInicio) + 60 ))
else 
 duracaoMin=$(($minFim - $minInicio))
fi

echo "A duração do jogo foi de ${duracaoHor} horas e ${duracaoMin} minutos"

#!/bin/bash
#estSeq26.sh

read -p "Digite o primeiro número: " num1
read -p "Digite o segundo número: " num2
		
if [ "$num1" -gt "$num2" && "$num1" % "$num2" -eq 0 || "$num2" -gt "$num1" && "$num2" % "$num1" -eq 0 ] ; then
 echo "O maior número é múltiplo do menor"
else
 echo "O maior número não é múltiplo do menor"
fi

#!/bin/bash
#estSeq27.sh

read -p "Digite o número de voltas: " numVoltas
read -p "Digite a extensão do circuito: " extCirc
read -p "Digite o tempo de duração: " tempDur
		
distTotal=$(echo " ($extCirc * $numVoltas) / 1000) " | bc)
velMed=$(echo "$distTotal / $tempDur" | bc);
echo "A velocidade média pecorrida é: ${velMed} km/h"

#!/bin/bash
#estSeq28.sh

read -p "Digite o preço atual do produto: " prAtual
read -p "Digite a venda mensal do produto: " vendMen
		
if [ "$vendMen" -lt 500 && "$prAtual" -lt 30 ] ; then
 prNovo=$(echo "$prAtual + ($prAtual * 0.10" | bc)
elif [ "$vendMen" -gte 500 && "$vendMen" -lt 1000 && "$prAtual" -gt 30 && "$prAtual" -lt 80 ] ; then
 prNovo=$(echo "$prAtual + ($prAtual * 0.15)" | bc)
elif [ "$vendMen" -gte 1000 && "$prAtual" -gte 80 ] ; then
 prNovo=$(echo "$prAtual - ($prAtual * 0.05)" | bc)
else 
 prNovo=$prAtual;
fi
		
echo "O preço novo do produto é ${prNovo} reais "

#!/bin/bash
#estSeq29.sh

read -p "Digite o tipo de investimento (1 = poupança e 2 = renda fixa): " tipo
read -p "Digite o valor do investimento: " valor
		
case $tipo in
 1) investimento=$(echo "$valor + ($valor * 0.03)" | bc) ;;
 2) investimento=$(echo "$valor + ($valor * 0.05)" | bc) ;;
 *) investimento=$valor ;;
esac 
		
echo "O valor de investimento é ${investimento} reais "

#!/bin/bash
#estSeq30.sh

read -p "Digite o ano de nascimento: " anoNasc
read -p "Digite o mês de nascimento: " mesNasc
read -p "Digite o dia de nascimento: " diaNasc
read -p "Digite o ano atual: " anoAt
read -p "Digite o mês atual: " mesAt
read -p "Digite o dia atual: " diaAt
		
if [ $mesAt - $mesNasc -lt 0 ] ; then
 mesRes=$(( (mesAt - mesNasc) + 12 ))
 anoRes=$(( (anoAt - anoNasc) - 1 ))
else 
 mesRes=$(( (mesAt - mesNasc) ))
 anoRes=$(( (anoAt - anoNasc) ))
fi	
		
if [ "$diaAt" - "$diaNasc" -lt 0 ] ; then
 if [ "$anoAt" % 4 -eq 0 && "$anoAt" % 100 -ne 0 && "$mesAt" - 1 -eq 2 || "$anoAt" % 400 -eq 0 && "$anoAt" % 100 -eq 0 && "$mesAt" - 1 -eq 2 ] ; then
  diaRes=$(( ($diaAt - $diaNasc) + 29 ))
 elif [ "$anoAt" % 4 -eq 0 && "$anoAt" % 100 -eq 0 && "$mesAt" - 1 -eq 2 || "$anoAt" % 400 -ne 0 && "$anoAt" % 100 -ne 0 && "$mesAt" - 1 -eq 2 ] ; then
  diaRes=$(( ($diaAt - $diaNasc) + 28 ))
 elif [ "$mesAt" % 2 -eq 1 && "$mesAt" -lt 8 || "$mesAt" % 2 -eq 0 && "$mesAt" > 7 ] ; then
  diaRes=$(( ($diaAt - $diaNasc) + 30 ))
 else
  diaRes=$(( ($diaAt - $diaNasc) + 31 ))
 fi			
else
 diaRes=$(( $diaAt - $diaNasc ))
echo "O resultado de sua idade é de ${anoRes} anos, ${mesRes} mes(es) e ${diaRes} dia(s)"

#!/bin/bash
#estSeq31.sh

num=10
		
for i in {$num..150}; do 
 quadrado=$(( (num * num) ))
 echo "O quadrado de ${i} ao quadro é: ${quadrado} "
done

#!/bin/bash
#estSeq32.sh

read -p "Digite o número de fatorial: " num
		
for i in {$num..1..-2}; do
 fat=$(( $fat * (num * (num - 1)) ))
done

echo "O resultado do fatorial ${num}  é: ${fat} "

#!/bin/bash
#estSeq33.sh

read -p "Digite o número para sequência: " num
		
while [ "$indx" -lt "$num" ]; do
 indx=$(($indx + 1));
 seq=$(echo " $seq + (1 / $indx)" | bc)
done

echo "O resultado da sequência ${num} é: ${seq} "

#!/bin/bash
#estSeq34.sh

read -p "Digite o número para tabuada: " num
		
while [ "$indx" -lt 10 ]; do
 indx=$(($indx + 1))
 mult=$(($num * $indx));
 echo "${num} x ${indx} = ${mult} "
done

#!/bin/bash
#estSeq35.sh

read -p "Digite o primeiro número: " num1
read -p "Digite o segundo número: " num2
		
if [ "$num2" -gt "$num1" ] ; then
 indx=$num2
else
 indx=$num1
fi
		
while [ "$indx" -gte "$num1" || "$indx" -gte "$num2" ] ; then
 if [ "$indx" % 2 -eq 1 ] ; then
  res=$(( $res + $indx ))
 fi
 indx--;
done
		
echo "A somatória de números ímpares entre os dois é: ${res} "

#!/bin/bash
#estSeq36.sh

echo "Digite o número para sequência de fatorial: " num
		
if [ "$num" -lt 2 ] ; then
 fat=1
fi
		
while [ "$indx" -lt "$num" ] ; then
 indx=$(($indx + 1))
			
 for indxFat in $(seq $indx 1 -1); do
  fat=$(($fat + ($num * $num) ))
 done
 seq=$(echo "$seq + (1 / $fat) " | bc)
 fat=0
done
		
echo "O resultado da sequência de fatorial é: ${seq} "
