# -*- coding: utf-8 -*-
"""tratamento_pesquisa_exemplo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H4KpOyR5gKW3XXAQV6ST6b7gAf86uDTL

Link da pesquisa:

https://forms.gle/f5BJZM8dDdKdQLoe8
"""

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

dados = pd.read_csv('/content/drive/MyDrive/Aulas Estatística (Python)/pesquisa_1.csv',
                      sep=',', encoding='UTF-8')
dados.head(23)

dados.shape

"""## **TRATAMENTO DOS DADOS**"""

# Excluir coluna
dados1 = dados.drop(columns=['Carimbo de data/hora'])
dados1.head(3)

# Renomear colunas
dados1 = dados1.rename(columns={'Qual a sua altura?': 'altura'})
dados1.head(2)

dados1.rename(columns={'Qual o seu RA?': 'ra','Qual a sua cor favorita?':'cor_favorita'},inplace=True)
dados1.head(2)

dados1 = dados1.rename(columns={'Qual o número de seu calçado?': 'numero_calcado'})
dados1.head(2)

# Valores faltantes (missing)
dados1.isnull().sum()

# Analisando as variáveis
dados1.dtypes

dados1.head(23)

# Trocando a vírgula para ponto para a conversão em float da coluna
dados1['altura'] = dados1['altura'].apply(lambda x: x.replace(',','.'))
dados1

dados1.dtypes

# Convertendo para float a coluna
dados1['altura'] = dados1['altura'].astype(float)
dados1.dtypes

# Deixando a primeira letra de todos os dados da coluna em minúsculo para a parte de desenvolver estatísticas
dados1['cor_favorita'] = dados1.cor_favorita.str.lower()
dados1.head(23)

# Corrigindo dados de número calçado que estão em formato "42-43" ou "44/45" para coletar o dois primeiros valores do intervalo de str pelo slice  

dados1 = dados1
dados1['numero_calcado'] = dados1['numero_calcado'].astype(str).str[:2]
dados1.head(23)

# Convertendo de uma forma segura a coluna em int com a correção anterior
dados1
dados1['numero_calcado'] = dados1['numero_calcado'].astype(int)
dados1.dtypes

# Gráfico de bolhas com plotly
import plotly.express as px
bolhas = px.scatter(dados1, x="cor_favorita", y="altura")
bolhas.show()

bolhas2 = px.scatter(dados1, x="altura", y="numero_calcado")
bolhas2.show()

# Salvando no diretório do projeto os dados tratados
dados1.to_csv('pesquisa_tratada_exemplo.csv', sep=',', encoding='UTF-8', index = False)

# Salvando no Drive
dados1.to_csv('/content/drive/MyDrive/Aulas Estatística (Python)/pesquisa_tratada_exemplo.csv', sep=',', encoding='UTF-8', index = False)