# -*- coding: utf-8 -*-
"""teste_uma_amostra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6z0r-JNb1gArmw8jbbfi50KDL65Gttw

## **TESTE PARA UMA AMOSTRA**
"""

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

enem_sp = pd.read_csv('/content/drive/MyDrive/Aulas Estatística (Python)/enem_2019_tratado.csv',
                    sep=",", encoding='iso-8859-1')

enem_sp.head()

colegioy = enem_sp.loc[enem_sp.CO_ESCOLA == 35151506.0]

colegioy.shape

colegioy.head()

"""1) Analisar a classificação das variáveis"""

colegioy.dtypes

"""2) Analisar valores missing"""

colegioy.isnull().sum()

"""3) Analisar outliers"""

import plotly.express as px

grafico = px.box(colegioy, y="NOTA_REDACAO")
grafico.show()

"""4) Analisar Normalidade"""

import scipy.stats as stats
import matplotlib.pyplot as plt

stats.probplot(colegioy['NOTA_REDACAO'], dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

"""CRITÉRIOS:

NÍVEL DE SIGNIFICÂNCIA DE 0,05 ou 5% (MAIS UTILIZADO).

Ho = distribuição é IGUAL à normal (p > 0,05).

Ha = distribuição é DIFERENTE DA NORMAL (p <= 0,05).
"""

import statsmodels
from statsmodels.stats.diagnostic import lilliefors
import scipy.stats as stats

# Teste Lilliefors (Kolmogorov_Sminorv)
statsmodels.stats.diagnostic.lilliefors(colegioy.NOTA_REDACAO, dist = 'norm')

# Teste Shapiro-Wilk
stats.shapiro(colegioy.NOTA_REDACAO)

"""## **TESTE Z**

AFIRMAÇÃO:
Média das notas do colégio é igual a média do Estado de São Paulo.

Ho = média é igual a de São Paulo : p > 0.05

Ha = média é diferente da de São Paulo : p <= 0.05
"""

from statsmodels.stats.weightstats import ztest

enem_sp.NOTA_REDACAO.describe()

stat, p = ztest(colegioy['NOTA_REDACAO'], value=593.0183221986639, )
print('Estatística de teste: {}'.format(stat.round(2)))
print('p-valor: {}'.format(p))

"""**INTERPRETAÇÃO:**

Teste estatístico: t = 7,18

p_valor = 7.17e-13

Conclusão: No nível de confiança de 5%, há evidências para afirmar que a média do colégio y é diferente da média do Estado de São Paulo.

## **TESTE t**

Ho = média é igual a de São Paulo : p > 0.05

Ha = média é diferente da de São Paulo : p <= 0.05
"""

import scipy.stats as stats

stat, p = stats.ttest_1samp(colegioy['NOTA_REDACAO'], popmean=593.018)
print('Estatística de teste: {}'.format(stat.round(2)))
print('p-valor: {}'.format(p.round(10)))

"""**INTERPRETAÇÃO:**

Teste estatístico: t = 7,18

p_valor = 6.72e-08

Conclusão: No nível de confiança de 5%, há evidências para afirmar que a média do colégio y é diferente da média do Estado de São Paulo.

**Região de aceitação/rejeição**

**Valores críticos**
"""

from scipy.stats import norm

alpha = 0.05

# Cálculo do z crítico Bicaudal
z_cri_B = norm.ppf(1 - alpha / 2)
# Cálculo do z crítico Unicaudal
z_cri_U = norm.ppf(1 - alpha)

print("Z crítico bicaudal:", z_cri_B)
print("Z crítico Unicaudal:", z_cri_U)

"""**Cálculo de Z**"""

colegioy.NOTA_REDACAO.describe()

enem_sp.NOTA_REDACAO.describe()

z=(colegioy.NOTA_REDACAO.mean()-enem_sp.NOTA_REDACAO.mean())/(enem_sp.NOTA_REDACAO.std()/(len(colegioy))**(1/2))
z