# -*- coding: utf-8 -*-
"""teste_2amostras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzGp5r1qQ38mbQLTexF8Syi4-bR5fxhC
"""

import numpy as np
import pandas as pd

enem_sp = pd.read_csv('/content/drive/MyDrive/Aulas Estatística (Python)/enem_2019_tratado.csv',
                      sep=',', encoding='iso-8859-1')

enem_sp.head()

"""Objetivo:
Analisar a diferença entre as médias de mulheres e homens para a nota de um dos componentes de redação do colégio x.





"""

colegiox = enem_sp.loc[enem_sp.CO_ESCOLA == 35017632.0]

colegiox.shape

colegiox.head()

colegiox_mulher = colegiox.loc[colegiox.SEXO == 'F']

colegiox_mulher.head()

colegiox_mulher.shape

colegiox_homem = colegiox.loc[colegiox.SEXO == 'M']

colegiox_homem.shape

colegiox_homem.head()

"""1) Analisar a classificação das variáveis"""

colegiox.dtypes

"""2) Analisar valores missing"""

colegiox.isnull().sum()

"""3) Analisar outliers"""

import plotly.express as px

grafico = px.box(colegiox_mulher, y="COMP5")
grafico.show()

grafico = px.box(colegiox_homem, y="COMP5")
grafico.show()

"""4) Analisar Normalidade

CRITÉRIOS:

NÍVEL DE SIGNIFICÂNCIA DE 0,05 ou 5% (MAIS UTILIZADO)

QUANDO p > 0,05 (distribuição normal).
"""

import scipy.stats as stats

# Teste Shapiro-Wilk
stats.shapiro(colegiox_mulher.COMP5)

# Teste Shapiro-Wilk
stats.shapiro(colegiox_homem.COMP5)

import scipy.stats as stats
import matplotlib.pyplot as plt

stats.probplot(colegiox_mulher['COMP5'], dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

stats.probplot(colegiox_homem['COMP5'], dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

"""**TESTE t-student**

Comparação das Médias das notas dos componentes 5 da redação do colégio Y.

Ho = NÃO HÁ DIFERENÇA ENTRE AS MÉDIAS DOS COMPONENTES : p > 0.05

Ha = HÁ DIFERENÇA ENTRE AS MÉDIAS DOS COMPONENTES : p <= 0.05
"""

import scipy.stats as stats

stat, p = stats.ttest_ind(colegiox_homem.COMP5, colegiox_mulher.COMP5, equal_var=False) # True só se o desvio padrão (std) for semelhante
print('Estatística de teste: {}'.format(stat.round(2)))
print('p-valor: {}'.format(p.round(10)))

"""**INTERPRETAÇÃO:**

Teste estatístico: -0,95

p_valor = 0,35

Conclusão: Estatisticamente, com nível de significância de 95%, não se pode concluir que a média do componente 5 de redação do colegio X seja diferente entre homens e mulheres.

**Caso fosse o teste Z, o código seria o seguinte:**

**TESTE Z para duas amostras independentes**

Comparação das Médias das notas do componente 5 da redação entre homens e mulheres do colégio X.

Ho = NÃO HÁ DIFERENÇA ENTRE AS MÉDIAS ENTRE HOMENS E MULHERES : p > 0.05

Ha = HÁ DIFERENÇA ENTRE AS MÉDIAS ENTRE HOMENS E MULHERES : p <= 0.05
"""

from statsmodels.stats.weightstats import ztest

stat, p = ztest(colegiox_mulher.COMP5, colegiox_homem.COMP5)
print('Estatística de teste: {}'.format(stat.round(2)))
print('p-valor: {}'.format(p))

colegiox_mulher.COMP5.describe()

colegiox_homem.COMP5.describe()