# -*- coding: utf-8 -*-
"""teste_mann_whitney.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JU3Tnce3I_wdbEoiVJQtAMhzRo9wWUbT

## TESTE MANN WHITNEY (soma de postos de Wilcoxon)

Teste Não paramétrico

Duas amostras independentes
"""

import numpy as np
import pandas as pd

enem_sp = pd.read_csv('/content/drive/MyDrive/Aulas Estatística (Python)/enem_2019_tratado.csv',
                      sep=',', encoding='iso-8859-1')

enem_sp.head()

"""Objetivo:
Analisar a diferença entre as MEDIANAS de mulheres e homens para as notas do colégio x.





"""

colegiox = enem_sp.loc[enem_sp.CO_ESCOLA == 35017632.0]

colegiox.shape

colegiox.head()

colegiox_mulher = colegiox.loc[colegiox.SEXO == 'F']

colegiox_mulher.head()

colegiox_mulher.shape

colegiox_homem = colegiox.loc[colegiox.SEXO == 'M']

colegiox_homem.shape

colegiox_homem.head()

"""1) Analisar a classificação das variáveis"""

colegiox.dtypes

"""2) Analisar valores missing"""

colegiox.isnull().sum()

"""3) Analisar Normalidade

CRITÉRIOS:

NÍVEL DE SIGNIFICÂNCIA DE 0,05 ou 5% (MAIS UTILIZADO)

QUANDO p > 0,05 (distribuição normal).
"""

import scipy.stats as stats

import matplotlib.pyplot as plt

# Teste Shapiro-Wilk - CIÊNCIAS DA NATUREZA
stats.shapiro(colegiox_mulher.NOTA_CN)

stats.probplot(colegiox_mulher['NOTA_CN'], dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

stats.shapiro(colegiox_homem.NOTA_CN)

stats.probplot(colegiox_homem['NOTA_CN'], dist="norm", plot=plt)
plt.title("Normal QQ plot")
plt.show()

"""**TESTE MANN WHITNEY**

Comparação das medianas das notas homens e mulheres do colégio X.

Ho = NÃO HÁ DIFERENÇA ENTRE AS MEDIANAS DAS NOTAS DE HOMENS E MULHERES : p > 0.05

Ha = HÁ DIFERENÇA ENTRE AS MEDIANAS DAS NOTAS ENTRE HOMENS E MULHERES : p <= 0.05
"""

import scipy.stats as stats

stat, p = stats.mannwhitneyu(colegiox_mulher.NOTA_CN, colegiox_homem.NOTA_CN)
print('Estatística de teste: {}'.format(stat.round(2)))
print('p-valor: {}'.format(p))

colegiox_mulher.NOTA_CN.describe()

colegiox_homem.NOTA_CN.describe()

import plotly.express as px

grafico = px.box(colegiox, x = 'SEXO', y="NOTA_CN")
grafico.show()

"""**Conclusão:** Estatisticamente, com intervalo de confiança de 95%, não se pode concluir que a mediana das notas de Matemática e Ciências da natureza do colegio X sejam diferentes entre homens e mulheres.


"""