
       01  TCONSAMG.
           05  BLANK SCREEN.
           05  LINE 02  COLUMN 01 
               VALUE  "                             *** CONSULT".
           05  LINE 02  COLUMN 41 
               VALUE  "A DE AMIGO ***".
           05  LINE 04  COLUMN 01 
               VALUE  "APELIDO :".
           05  LINE 04  COLUMN 41 
               VALUE  "  EMAIL :".
           05  LINE 22  COLUMN 01 
               VALUE  "MENSAGEN :".
