
       01  TCONSAREA2.
           05  BLANK SCREEN.
           05  LINE 02  COLUMN 01 
               VALUE  "                             *** CONSULT".
           05  LINE 02  COLUMN 41 
               VALUE  "A DE AREA ***".
           05  LINE 04  COLUMN 01 
               VALUE  "    AREA :      NOME :".
           05  LINE 04  COLUMN 41 
               VALUE  "       ESTRUTURA :".
           05  LINE 22  COLUMN 01 
               VALUE  "    MENSAGEM :".
