
       01  TCONSVEN.
           05  BLANK SCREEN.
           05  LINE 02  COLUMN 01 
               VALUE  "                            *** CONSULTA".
           05  LINE 02  COLUMN 41 
               VALUE  " DE VEICULO ***".
           05  LINE 04  COLUMN 01 
               VALUE  "   PLACA :         NOME PROPRIETARIO :".
           05  LINE 22  COLUMN 01 
               VALUE  "   MENSAGEM :".
