# -*- coding: utf-8 -*-
"""estatística_descritiva.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGcvsKq6Ya28CNhyaK-lRyJnCFcXUlmp

# **ESTATÍSTICA DESCRITIVA**
"""

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Aulas Estatística (Python)/pesquisa_tratada_exemplo.csv',
                      sep=',', encoding='UTF-8')
df.head(60)

df.shape

"""## **Medidas de tendência central**

### Média
"""

df['altura'].mean()

round(df['altura'].mean(),2)

"""### Mediana"""

df.altura.median()

"""### Moda"""

df['altura'].mode()

"""## **Medidas de dispersão**"""

df['altura'].var() # Variância amostral

df.altura.var(ddof=0) #Variância Populacional

df.altura.std() # Desvio padrão amostral

# sqrt = raiz quadrada
np.sqrt(df['altura'].var(ddof=0)) # Desvio padrão populacional

df.altura.mean() # Média

# Desvio absoluto
(df.altura - df.altura.mean()).abs()

# Soma do desvio absoluto
sum((df.altura - df.altura.mean()).abs())

df.describe()

"""## **Medidas de Posição**"""

# Mínimo
df['altura'].min()

# Máximo
df.altura.max()

# Primeiro Quartil
df['altura'].quantile(q=0.25)

# Segundo Quartil (Mediana)
df['altura'].quantile(q=0.5)

# Terceiro Quartil
df['altura'].quantile(q=0.75)

# Percentil 90 (p90)
df['altura'].quantile(q=0.90)

df.altura.describe()

"""## **Gráfico BoxPlot e Outliers**

### Plotly
"""

import plotly.express as px

grafico = px.box(df, y="altura")
grafico.show()